/*
 * Copyright 2014 Hieu Rocker
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.buaa.ct.comment.emoji;


public class Objects {
    public static final EmojiIcon[] DATA = new EmojiIcon[]{
            EmojiIcon.fromCodePoint(0x1f38d),
            EmojiIcon.fromCodePoint(0x1f49d),
            EmojiIcon.fromCodePoint(0x1f38e),
            EmojiIcon.fromCodePoint(0x1f392),
            EmojiIcon.fromCodePoint(0x1f393),
            EmojiIcon.fromCodePoint(0x1f38f),
            EmojiIcon.fromCodePoint(0x1f386),
            EmojiIcon.fromCodePoint(0x1f387),
            EmojiIcon.fromCodePoint(0x1f390),
            EmojiIcon.fromCodePoint(0x1f391),
            EmojiIcon.fromCodePoint(0x1f383),
            EmojiIcon.fromCodePoint(0x1f47b),
            EmojiIcon.fromCodePoint(0x1f385),
            EmojiIcon.fromCodePoint(0x1f384),
            EmojiIcon.fromCodePoint(0x1f381),
            EmojiIcon.fromCodePoint(0x1f38b),
            EmojiIcon.fromCodePoint(0x1f389),
            EmojiIcon.fromCodePoint(0x1f38a),
            EmojiIcon.fromCodePoint(0x1f388),
            EmojiIcon.fromCodePoint(0x1f38c),
            EmojiIcon.fromCodePoint(0x1f52e),
            EmojiIcon.fromCodePoint(0x1f3a5),
            EmojiIcon.fromCodePoint(0x1f4f7),
            EmojiIcon.fromCodePoint(0x1f4f9),
            EmojiIcon.fromCodePoint(0x1f4fc),
            EmojiIcon.fromCodePoint(0x1f4bf),
            EmojiIcon.fromCodePoint(0x1f4c0),
            EmojiIcon.fromCodePoint(0x1f4bd),
            EmojiIcon.fromCodePoint(0x1f4be),
            EmojiIcon.fromCodePoint(0x1f4bb),
            EmojiIcon.fromCodePoint(0x1f4f1),
            EmojiIcon.fromChar((char) 0x260e),
            EmojiIcon.fromCodePoint(0x1f4de),
            EmojiIcon.fromCodePoint(0x1f4df),
            EmojiIcon.fromCodePoint(0x1f4e0),
            EmojiIcon.fromCodePoint(0x1f4e1),
            EmojiIcon.fromCodePoint(0x1f4fa),
            EmojiIcon.fromCodePoint(0x1f4fb),
            EmojiIcon.fromCodePoint(0x1f508),
            EmojiIcon.fromCodePoint(0x1f509),
            EmojiIcon.fromCodePoint(0x1f50a),
            EmojiIcon.fromCodePoint(0x1f507),
            EmojiIcon.fromCodePoint(0x1f514),
            EmojiIcon.fromCodePoint(0x1f515),
            EmojiIcon.fromCodePoint(0x1f4e2),
            EmojiIcon.fromCodePoint(0x1f4e3),
            EmojiIcon.fromChar((char) 0x23f3),
            EmojiIcon.fromChar((char) 0x231b),
            EmojiIcon.fromChar((char) 0x23f0),
            EmojiIcon.fromChar((char) 0x231a),
            EmojiIcon.fromCodePoint(0x1f513),
            EmojiIcon.fromCodePoint(0x1f512),
            EmojiIcon.fromCodePoint(0x1f50f),
            EmojiIcon.fromCodePoint(0x1f510),
            EmojiIcon.fromCodePoint(0x1f511),
            EmojiIcon.fromCodePoint(0x1f50e),
            EmojiIcon.fromCodePoint(0x1f4a1),
            EmojiIcon.fromCodePoint(0x1f526),
            EmojiIcon.fromCodePoint(0x1f506),
            EmojiIcon.fromCodePoint(0x1f505),
            EmojiIcon.fromCodePoint(0x1f50c),
            EmojiIcon.fromCodePoint(0x1f50b),
            EmojiIcon.fromCodePoint(0x1f50d),
            EmojiIcon.fromCodePoint(0x1f6c1),
            EmojiIcon.fromCodePoint(0x1f6c0),
            EmojiIcon.fromCodePoint(0x1f6bf),
            EmojiIcon.fromCodePoint(0x1f6bd),
            EmojiIcon.fromCodePoint(0x1f527),
            EmojiIcon.fromCodePoint(0x1f529),
            EmojiIcon.fromCodePoint(0x1f528),
            EmojiIcon.fromCodePoint(0x1f6aa),
            EmojiIcon.fromCodePoint(0x1f6ac),
            EmojiIcon.fromCodePoint(0x1f4a3),
            EmojiIcon.fromCodePoint(0x1f52b),
            EmojiIcon.fromCodePoint(0x1f52a),
            EmojiIcon.fromCodePoint(0x1f48a),
            EmojiIcon.fromCodePoint(0x1f489),
            EmojiIcon.fromCodePoint(0x1f4b0),
            EmojiIcon.fromCodePoint(0x1f4b4),
            EmojiIcon.fromCodePoint(0x1f4b5),
            EmojiIcon.fromCodePoint(0x1f4b7),
            EmojiIcon.fromCodePoint(0x1f4b6),
            EmojiIcon.fromCodePoint(0x1f4b3),
            EmojiIcon.fromCodePoint(0x1f4b8),
            EmojiIcon.fromCodePoint(0x1f4f2),
            EmojiIcon.fromCodePoint(0x1f4e7),
            EmojiIcon.fromCodePoint(0x1f4e5),
            EmojiIcon.fromCodePoint(0x1f4e4),
            EmojiIcon.fromChar((char) 0x2709),
            EmojiIcon.fromCodePoint(0x1f4e9),
            EmojiIcon.fromCodePoint(0x1f4e8),
            EmojiIcon.fromCodePoint(0x1f4ef),
            EmojiIcon.fromCodePoint(0x1f4eb),
            EmojiIcon.fromCodePoint(0x1f4ea),
            EmojiIcon.fromCodePoint(0x1f4ec),
            EmojiIcon.fromCodePoint(0x1f4ed),
            EmojiIcon.fromCodePoint(0x1f4ee),
            EmojiIcon.fromCodePoint(0x1f4e6),
            EmojiIcon.fromCodePoint(0x1f4dd),
            EmojiIcon.fromCodePoint(0x1f4c4),
            EmojiIcon.fromCodePoint(0x1f4c3),
            EmojiIcon.fromCodePoint(0x1f4d1),
            EmojiIcon.fromCodePoint(0x1f4ca),
            EmojiIcon.fromCodePoint(0x1f4c8),
            EmojiIcon.fromCodePoint(0x1f4c9),
            EmojiIcon.fromCodePoint(0x1f4dc),
            EmojiIcon.fromCodePoint(0x1f4cb),
            EmojiIcon.fromCodePoint(0x1f4c5),
            EmojiIcon.fromCodePoint(0x1f4c6),
            EmojiIcon.fromCodePoint(0x1f4c7),
            EmojiIcon.fromCodePoint(0x1f4c1),
            EmojiIcon.fromCodePoint(0x1f4c2),
            EmojiIcon.fromChar((char) 0x2702),
            EmojiIcon.fromCodePoint(0x1f4cc),
            EmojiIcon.fromCodePoint(0x1f4ce),
            EmojiIcon.fromChar((char) 0x2712),
            EmojiIcon.fromChar((char) 0x270f),
            EmojiIcon.fromCodePoint(0x1f4cf),
            EmojiIcon.fromCodePoint(0x1f4d0),
            EmojiIcon.fromCodePoint(0x1f4d5),
            EmojiIcon.fromCodePoint(0x1f4d7),
            EmojiIcon.fromCodePoint(0x1f4d8),
            EmojiIcon.fromCodePoint(0x1f4d9),
            EmojiIcon.fromCodePoint(0x1f4d3),
            EmojiIcon.fromCodePoint(0x1f4d4),
            EmojiIcon.fromCodePoint(0x1f4d2),
            EmojiIcon.fromCodePoint(0x1f4da),
            EmojiIcon.fromCodePoint(0x1f4d6),
            EmojiIcon.fromCodePoint(0x1f516),
            EmojiIcon.fromCodePoint(0x1f4db),
            EmojiIcon.fromCodePoint(0x1f52c),
            EmojiIcon.fromCodePoint(0x1f52d),
            EmojiIcon.fromCodePoint(0x1f4f0),
            EmojiIcon.fromCodePoint(0x1f3a8),
            EmojiIcon.fromCodePoint(0x1f3ac),
            EmojiIcon.fromCodePoint(0x1f3a4),
            EmojiIcon.fromCodePoint(0x1f3a7),
            EmojiIcon.fromCodePoint(0x1f3bc),
            EmojiIcon.fromCodePoint(0x1f3b5),
            EmojiIcon.fromCodePoint(0x1f3b6),
            EmojiIcon.fromCodePoint(0x1f3b9),
            EmojiIcon.fromCodePoint(0x1f3bb),
            EmojiIcon.fromCodePoint(0x1f3ba),
            EmojiIcon.fromCodePoint(0x1f3b7),
            EmojiIcon.fromCodePoint(0x1f3b8),
            EmojiIcon.fromCodePoint(0x1f47e),
            EmojiIcon.fromCodePoint(0x1f3ae),
            EmojiIcon.fromCodePoint(0x1f0cf),
            EmojiIcon.fromCodePoint(0x1f3b4),
            EmojiIcon.fromCodePoint(0x1f004),
            EmojiIcon.fromCodePoint(0x1f3b2),
            EmojiIcon.fromCodePoint(0x1f3af),
            EmojiIcon.fromCodePoint(0x1f3c8),
            EmojiIcon.fromCodePoint(0x1f3c0),
            EmojiIcon.fromChar((char) 0x26bd),
            EmojiIcon.fromChar((char) 0x26be),
            EmojiIcon.fromCodePoint(0x1f3be),
            EmojiIcon.fromCodePoint(0x1f3b1),
            EmojiIcon.fromCodePoint(0x1f3c9),
            EmojiIcon.fromCodePoint(0x1f3b3),
            EmojiIcon.fromChar((char) 0x26f3),
            EmojiIcon.fromCodePoint(0x1f6b5),
            EmojiIcon.fromCodePoint(0x1f6b4),
            EmojiIcon.fromCodePoint(0x1f3c1),
            EmojiIcon.fromCodePoint(0x1f3c7),
            EmojiIcon.fromCodePoint(0x1f3c6),
            EmojiIcon.fromCodePoint(0x1f3bf),
            EmojiIcon.fromCodePoint(0x1f3c2),
            EmojiIcon.fromCodePoint(0x1f3ca),
            EmojiIcon.fromCodePoint(0x1f3c4),
            EmojiIcon.fromCodePoint(0x1f3a3),
            EmojiIcon.fromChar((char) 0x2615),
            EmojiIcon.fromCodePoint(0x1f375),
            EmojiIcon.fromCodePoint(0x1f376),
            EmojiIcon.fromCodePoint(0x1f37c),
            EmojiIcon.fromCodePoint(0x1f37a),
            EmojiIcon.fromCodePoint(0x1f37b),
            EmojiIcon.fromCodePoint(0x1f378),
            EmojiIcon.fromCodePoint(0x1f379),
            EmojiIcon.fromCodePoint(0x1f377),
            EmojiIcon.fromCodePoint(0x1f374),
            EmojiIcon.fromCodePoint(0x1f355),
            EmojiIcon.fromCodePoint(0x1f354),
            EmojiIcon.fromCodePoint(0x1f35f),
            EmojiIcon.fromCodePoint(0x1f357),
            EmojiIcon.fromCodePoint(0x1f356),
            EmojiIcon.fromCodePoint(0x1f35d),
            EmojiIcon.fromCodePoint(0x1f35b),
            EmojiIcon.fromCodePoint(0x1f364),
            EmojiIcon.fromCodePoint(0x1f371),
            EmojiIcon.fromCodePoint(0x1f363),
            EmojiIcon.fromCodePoint(0x1f365),
            EmojiIcon.fromCodePoint(0x1f359),
            EmojiIcon.fromCodePoint(0x1f358),
            EmojiIcon.fromCodePoint(0x1f35a),
            EmojiIcon.fromCodePoint(0x1f35c),
            EmojiIcon.fromCodePoint(0x1f372),
            EmojiIcon.fromCodePoint(0x1f362),
            EmojiIcon.fromCodePoint(0x1f361),
            EmojiIcon.fromCodePoint(0x1f373),
            EmojiIcon.fromCodePoint(0x1f35e),
            EmojiIcon.fromCodePoint(0x1f369),
            EmojiIcon.fromCodePoint(0x1f36e),
            EmojiIcon.fromCodePoint(0x1f366),
            EmojiIcon.fromCodePoint(0x1f368),
            EmojiIcon.fromCodePoint(0x1f367),
            EmojiIcon.fromCodePoint(0x1f382),
            EmojiIcon.fromCodePoint(0x1f370),
            EmojiIcon.fromCodePoint(0x1f36a),
            EmojiIcon.fromCodePoint(0x1f36b),
            EmojiIcon.fromCodePoint(0x1f36c),
            EmojiIcon.fromCodePoint(0x1f36d),
            EmojiIcon.fromCodePoint(0x1f36f),
            EmojiIcon.fromCodePoint(0x1f34e),
            EmojiIcon.fromCodePoint(0x1f34f),
            EmojiIcon.fromCodePoint(0x1f34a),
            EmojiIcon.fromCodePoint(0x1f34b),
            EmojiIcon.fromCodePoint(0x1f352),
            EmojiIcon.fromCodePoint(0x1f347),
            EmojiIcon.fromCodePoint(0x1f349),
            EmojiIcon.fromCodePoint(0x1f353),
            EmojiIcon.fromCodePoint(0x1f351),
            EmojiIcon.fromCodePoint(0x1f348),
            EmojiIcon.fromCodePoint(0x1f34c),
            EmojiIcon.fromCodePoint(0x1f350),
            EmojiIcon.fromCodePoint(0x1f34d),
            EmojiIcon.fromCodePoint(0x1f360),
            EmojiIcon.fromCodePoint(0x1f346),
            EmojiIcon.fromCodePoint(0x1f345),
            EmojiIcon.fromCodePoint(0x1f33d),
    };
}
