/*
 * Copyright 2014 Hieu Rocker
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.buaa.ct.comment.emoji;


public class Places {
    public static final EmojiIcon[] DATA = new EmojiIcon[]{
            EmojiIcon.fromCodePoint(0x1f3e0),
            EmojiIcon.fromCodePoint(0x1f3e1),
            EmojiIcon.fromCodePoint(0x1f3eb),
            EmojiIcon.fromCodePoint(0x1f3e2),
            EmojiIcon.fromCodePoint(0x1f3e3),
            EmojiIcon.fromCodePoint(0x1f3e5),
            EmojiIcon.fromCodePoint(0x1f3e6),
            EmojiIcon.fromCodePoint(0x1f3ea),
            EmojiIcon.fromCodePoint(0x1f3e9),
            EmojiIcon.fromCodePoint(0x1f3e8),
            EmojiIcon.fromCodePoint(0x1f492),
            EmojiIcon.fromChar((char) 0x26ea),
            EmojiIcon.fromCodePoint(0x1f3ec),
            EmojiIcon.fromCodePoint(0x1f3e4),
            EmojiIcon.fromCodePoint(0x1f307),
            EmojiIcon.fromCodePoint(0x1f306),
            EmojiIcon.fromCodePoint(0x1f3ef),
            EmojiIcon.fromCodePoint(0x1f3f0),
            EmojiIcon.fromChar((char) 0x26fa),
            EmojiIcon.fromCodePoint(0x1f3ed),
            EmojiIcon.fromCodePoint(0x1f5fc),
            EmojiIcon.fromCodePoint(0x1f5fe),
            EmojiIcon.fromCodePoint(0x1f5fb),
            EmojiIcon.fromCodePoint(0x1f304),
            EmojiIcon.fromCodePoint(0x1f305),
            EmojiIcon.fromCodePoint(0x1f303),
            EmojiIcon.fromCodePoint(0x1f5fd),
            EmojiIcon.fromCodePoint(0x1f309),
            EmojiIcon.fromCodePoint(0x1f3a0),
            EmojiIcon.fromCodePoint(0x1f3a1),
            EmojiIcon.fromChar((char) 0x26f2),
            EmojiIcon.fromCodePoint(0x1f3a2),
            EmojiIcon.fromCodePoint(0x1f6a2),
            EmojiIcon.fromChar((char) 0x26f5),
            EmojiIcon.fromCodePoint(0x1f6a4),
            EmojiIcon.fromCodePoint(0x1f6a3),
            EmojiIcon.fromChar((char) 0x2693),
            EmojiIcon.fromCodePoint(0x1f680),
            EmojiIcon.fromChar((char) 0x2708),
            EmojiIcon.fromCodePoint(0x1f4ba),
            EmojiIcon.fromCodePoint(0x1f681),
            EmojiIcon.fromCodePoint(0x1f682),
            EmojiIcon.fromCodePoint(0x1f68a),
            EmojiIcon.fromCodePoint(0x1f689),
            EmojiIcon.fromCodePoint(0x1f69e),
            EmojiIcon.fromCodePoint(0x1f686),
            EmojiIcon.fromCodePoint(0x1f684),
            EmojiIcon.fromCodePoint(0x1f685),
            EmojiIcon.fromCodePoint(0x1f688),
            EmojiIcon.fromCodePoint(0x1f687),
            EmojiIcon.fromCodePoint(0x1f69d),
            EmojiIcon.fromCodePoint(0x1f68b),
            EmojiIcon.fromCodePoint(0x1f683),
            EmojiIcon.fromCodePoint(0x1f68e),
            EmojiIcon.fromCodePoint(0x1f68c),
            EmojiIcon.fromCodePoint(0x1f68d),
            EmojiIcon.fromCodePoint(0x1f699),
            EmojiIcon.fromCodePoint(0x1f698),
            EmojiIcon.fromCodePoint(0x1f697),
            EmojiIcon.fromCodePoint(0x1f695),
            EmojiIcon.fromCodePoint(0x1f696),
            EmojiIcon.fromCodePoint(0x1f69b),
            EmojiIcon.fromCodePoint(0x1f69a),
            EmojiIcon.fromCodePoint(0x1f6a8),
            EmojiIcon.fromCodePoint(0x1f693),
            EmojiIcon.fromCodePoint(0x1f694),
            EmojiIcon.fromCodePoint(0x1f692),
            EmojiIcon.fromCodePoint(0x1f691),
            EmojiIcon.fromCodePoint(0x1f690),
            EmojiIcon.fromCodePoint(0x1f6b2),
            EmojiIcon.fromCodePoint(0x1f6a1),
            EmojiIcon.fromCodePoint(0x1f69f),
            EmojiIcon.fromCodePoint(0x1f6a0),
            EmojiIcon.fromCodePoint(0x1f69c),
            EmojiIcon.fromCodePoint(0x1f488),
            EmojiIcon.fromCodePoint(0x1f68f),
            EmojiIcon.fromCodePoint(0x1f3ab),
            EmojiIcon.fromCodePoint(0x1f6a6),
            EmojiIcon.fromCodePoint(0x1f6a5),
            EmojiIcon.fromChar((char) 0x26a0),
            EmojiIcon.fromCodePoint(0x1f6a7),
            EmojiIcon.fromCodePoint(0x1f530),
            EmojiIcon.fromChar((char) 0x26fd),
            EmojiIcon.fromCodePoint(0x1f3ee),
            EmojiIcon.fromCodePoint(0x1f3b0),
            EmojiIcon.fromChar((char) 0x2668),
            EmojiIcon.fromCodePoint(0x1f5ff),
            EmojiIcon.fromCodePoint(0x1f3aa),
            EmojiIcon.fromCodePoint(0x1f3ad),
            EmojiIcon.fromCodePoint(0x1f4cd),
            EmojiIcon.fromCodePoint(0x1f6a9),
            EmojiIcon.fromChars("\ud83c\uddef\ud83c\uddf5"),
            EmojiIcon.fromChars("\ud83c\uddf0\ud83c\uddf7"),
            EmojiIcon.fromChars("\ud83c\udde9\ud83c\uddea"),
            EmojiIcon.fromChars("\ud83c\udde8\ud83c\uddf3"),
            EmojiIcon.fromChars("\ud83c\uddfa\ud83c\uddf8"),
            EmojiIcon.fromChars("\ud83c\uddeb\ud83c\uddf7"),
            EmojiIcon.fromChars("\ud83c\uddea\ud83c\uddf8"),
            EmojiIcon.fromChars("\ud83c\uddee\ud83c\uddf9"),
            EmojiIcon.fromChars("\ud83c\uddf7\ud83c\uddfa"),
            EmojiIcon.fromChars("\ud83c\uddec\ud83c\udde7"),
    };
}
