/*
 * Copyright 2014 Hieu Rocker
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.buaa.ct.comment.emoji;

/**
 * @author Hieu Rocker (rockerhieu@gmail.com)
 */
public class Symbols {
    public static final EmojiIcon[] DATA = new EmojiIcon[]{
            EmojiIcon.fromChars("\u0031\u20e3"),
            EmojiIcon.fromChars("\u0032\u20e3"),
            EmojiIcon.fromChars("\u0033\u20e3"),
            EmojiIcon.fromChars("\u0034\u20e3"),
            EmojiIcon.fromChars("\u0035\u20e3"),
            EmojiIcon.fromChars("\u0036\u20e3"),
            EmojiIcon.fromChars("\u0037\u20e3"),
            EmojiIcon.fromChars("\u0038\u20e3"),
            EmojiIcon.fromChars("\u0039\u20e3"),
            EmojiIcon.fromChars("\u0030\u20e3"),
            EmojiIcon.fromCodePoint(0x1f51f),
            EmojiIcon.fromCodePoint(0x1f522),
            EmojiIcon.fromChars("\u0023\u20e3"),
            EmojiIcon.fromCodePoint(0x1f523),
            EmojiIcon.fromChar((char) 0x2b06),
            EmojiIcon.fromChar((char) 0x2b07),
            EmojiIcon.fromChar((char) 0x2b05),
            EmojiIcon.fromChar((char) 0x27a1),
            EmojiIcon.fromCodePoint(0x1f520),
            EmojiIcon.fromCodePoint(0x1f521),
            EmojiIcon.fromCodePoint(0x1f524),
            EmojiIcon.fromChar((char) 0x2197),
            EmojiIcon.fromChar((char) 0x2196),
            EmojiIcon.fromChar((char) 0x2198),
            EmojiIcon.fromChar((char) 0x2199),
            EmojiIcon.fromChar((char) 0x2194),
            EmojiIcon.fromChar((char) 0x2195),
            EmojiIcon.fromCodePoint(0x1f504),
            EmojiIcon.fromChar((char) 0x25c0),
            EmojiIcon.fromChar((char) 0x25b6),
            EmojiIcon.fromCodePoint(0x1f53c),
            EmojiIcon.fromCodePoint(0x1f53d),
            EmojiIcon.fromChar((char) 0x21a9),
            EmojiIcon.fromChar((char) 0x21aa),
            EmojiIcon.fromChar((char) 0x2139),
            EmojiIcon.fromChar((char) 0x23ea),
            EmojiIcon.fromChar((char) 0x23e9),
            EmojiIcon.fromChar((char) 0x23eb),
            EmojiIcon.fromChar((char) 0x23ec),
            EmojiIcon.fromChar((char) 0x2935),
            EmojiIcon.fromChar((char) 0x2934),
            EmojiIcon.fromCodePoint(0x1f197),
            EmojiIcon.fromCodePoint(0x1f500),
            EmojiIcon.fromCodePoint(0x1f501),
            EmojiIcon.fromCodePoint(0x1f502),
            EmojiIcon.fromCodePoint(0x1f195),
            EmojiIcon.fromCodePoint(0x1f199),
            EmojiIcon.fromCodePoint(0x1f192),
            EmojiIcon.fromCodePoint(0x1f193),
            EmojiIcon.fromCodePoint(0x1f196),
            EmojiIcon.fromCodePoint(0x1f4f6),
            EmojiIcon.fromCodePoint(0x1f3a6),
            EmojiIcon.fromCodePoint(0x1f201),
            EmojiIcon.fromCodePoint(0x1f22f),
            EmojiIcon.fromCodePoint(0x1f233),
            EmojiIcon.fromCodePoint(0x1f235),
            EmojiIcon.fromCodePoint(0x1f234),
            EmojiIcon.fromCodePoint(0x1f232),
            EmojiIcon.fromCodePoint(0x1f250),
            EmojiIcon.fromCodePoint(0x1f239),
            EmojiIcon.fromCodePoint(0x1f23a),
            EmojiIcon.fromCodePoint(0x1f236),
            EmojiIcon.fromCodePoint(0x1f21a),
            EmojiIcon.fromCodePoint(0x1f6bb),
            EmojiIcon.fromCodePoint(0x1f6b9),
            EmojiIcon.fromCodePoint(0x1f6ba),
            EmojiIcon.fromCodePoint(0x1f6bc),
            EmojiIcon.fromCodePoint(0x1f6be),
            EmojiIcon.fromCodePoint(0x1f6b0),
            EmojiIcon.fromCodePoint(0x1f6ae),
            EmojiIcon.fromCodePoint(0x1f17f),
            EmojiIcon.fromChar((char) 0x267f),
            EmojiIcon.fromCodePoint(0x1f6ad),
            EmojiIcon.fromCodePoint(0x1f237),
            EmojiIcon.fromCodePoint(0x1f238),
            EmojiIcon.fromCodePoint(0x1f202),
            EmojiIcon.fromChar((char) 0x24c2),
            EmojiIcon.fromCodePoint(0x1f6c2),
            EmojiIcon.fromCodePoint(0x1f6c4),
            EmojiIcon.fromCodePoint(0x1f6c5),
            EmojiIcon.fromCodePoint(0x1f6c3),
            EmojiIcon.fromCodePoint(0x1f251),
            EmojiIcon.fromChar((char) 0x3299),
            EmojiIcon.fromChar((char) 0x3297),
            EmojiIcon.fromCodePoint(0x1f191),
            EmojiIcon.fromCodePoint(0x1f198),
            EmojiIcon.fromCodePoint(0x1f194),
            EmojiIcon.fromCodePoint(0x1f6ab),
            EmojiIcon.fromCodePoint(0x1f51e),
            EmojiIcon.fromCodePoint(0x1f4f5),
            EmojiIcon.fromCodePoint(0x1f6af),
            EmojiIcon.fromCodePoint(0x1f6b1),
            EmojiIcon.fromCodePoint(0x1f6b3),
            EmojiIcon.fromCodePoint(0x1f6b7),
            EmojiIcon.fromCodePoint(0x1f6b8),
            EmojiIcon.fromChar((char) 0x26d4),
            EmojiIcon.fromChar((char) 0x2733),
            EmojiIcon.fromChar((char) 0x2747),
            EmojiIcon.fromChar((char) 0x274e),
            EmojiIcon.fromChar((char) 0x2705),
            EmojiIcon.fromChar((char) 0x2734),
            EmojiIcon.fromCodePoint(0x1f49f),
            EmojiIcon.fromCodePoint(0x1f19a),
            EmojiIcon.fromCodePoint(0x1f4f3),
            EmojiIcon.fromCodePoint(0x1f4f4),
            EmojiIcon.fromCodePoint(0x1f170),
            EmojiIcon.fromCodePoint(0x1f171),
            EmojiIcon.fromCodePoint(0x1f18e),
            EmojiIcon.fromCodePoint(0x1f17e),
            EmojiIcon.fromCodePoint(0x1f4a0),
            EmojiIcon.fromChar((char) 0x27bf),
            EmojiIcon.fromChar((char) 0x267b),
            EmojiIcon.fromChar((char) 0x2648),
            EmojiIcon.fromChar((char) 0x2649),
            EmojiIcon.fromChar((char) 0x264a),
            EmojiIcon.fromChar((char) 0x264b),
            EmojiIcon.fromChar((char) 0x264c),
            EmojiIcon.fromChar((char) 0x264d),
            EmojiIcon.fromChar((char) 0x264e),
            EmojiIcon.fromChar((char) 0x264f),
            EmojiIcon.fromChar((char) 0x2650),
            EmojiIcon.fromChar((char) 0x2651),
            EmojiIcon.fromChar((char) 0x2652),
            EmojiIcon.fromChar((char) 0x2653),
            EmojiIcon.fromChar((char) 0x26ce),
            EmojiIcon.fromCodePoint(0x1f52f),
            EmojiIcon.fromCodePoint(0x1f3e7),
            EmojiIcon.fromCodePoint(0x1f4b9),
            EmojiIcon.fromCodePoint(0x1f4b2),
            EmojiIcon.fromCodePoint(0x1f4b1),
//            Emoji.fromChar((char)0x00a9),
//            Emoji.fromChar((char)0x00ae),
            EmojiIcon.fromChar((char) 0xe24e),
            EmojiIcon.fromChar((char) 0xe24f),

            EmojiIcon.fromChar((char) 0x2122),
            EmojiIcon.fromChar((char) 0x274c),
            EmojiIcon.fromChar((char) 0x203c),
            EmojiIcon.fromChar((char) 0x2049),
            EmojiIcon.fromChar((char) 0x2757),
            EmojiIcon.fromChar((char) 0x2753),
            EmojiIcon.fromChar((char) 0x2755),
            EmojiIcon.fromChar((char) 0x2754),
            EmojiIcon.fromChar((char) 0x2b55),
            EmojiIcon.fromCodePoint(0x1f51d),
            EmojiIcon.fromCodePoint(0x1f51a),
            EmojiIcon.fromCodePoint(0x1f519),
            EmojiIcon.fromCodePoint(0x1f51b),
            EmojiIcon.fromCodePoint(0x1f51c),
            EmojiIcon.fromCodePoint(0x1f503),
            EmojiIcon.fromCodePoint(0x1f55b),
            EmojiIcon.fromCodePoint(0x1f567),
            EmojiIcon.fromCodePoint(0x1f550),
            EmojiIcon.fromCodePoint(0x1f55c),
            EmojiIcon.fromCodePoint(0x1f551),
            EmojiIcon.fromCodePoint(0x1f55d),
            EmojiIcon.fromCodePoint(0x1f552),
            EmojiIcon.fromCodePoint(0x1f55e),
            EmojiIcon.fromCodePoint(0x1f553),
            EmojiIcon.fromCodePoint(0x1f55f),
            EmojiIcon.fromCodePoint(0x1f554),
            EmojiIcon.fromCodePoint(0x1f560),
            EmojiIcon.fromCodePoint(0x1f555),
            EmojiIcon.fromCodePoint(0x1f556),
            EmojiIcon.fromCodePoint(0x1f557),
            EmojiIcon.fromCodePoint(0x1f558),
            EmojiIcon.fromCodePoint(0x1f559),
            EmojiIcon.fromCodePoint(0x1f55a),
            EmojiIcon.fromCodePoint(0x1f561),
            EmojiIcon.fromCodePoint(0x1f562),
            EmojiIcon.fromCodePoint(0x1f563),
            EmojiIcon.fromCodePoint(0x1f564),
            EmojiIcon.fromCodePoint(0x1f565),
            EmojiIcon.fromCodePoint(0x1f566),
            EmojiIcon.fromChar((char) 0x2716),
            EmojiIcon.fromChar((char) 0x2795),
            EmojiIcon.fromChar((char) 0x2796),
            EmojiIcon.fromChar((char) 0x2797),
            EmojiIcon.fromChar((char) 0x2660),
            EmojiIcon.fromChar((char) 0x2665),
            EmojiIcon.fromChar((char) 0x2663),
            EmojiIcon.fromChar((char) 0x2666),
            EmojiIcon.fromCodePoint(0x1f4ae),
            EmojiIcon.fromCodePoint(0x1f4af),
            EmojiIcon.fromChar((char) 0x2714),
            EmojiIcon.fromChar((char) 0x2611),
            EmojiIcon.fromCodePoint(0x1f518),
            EmojiIcon.fromCodePoint(0x1f517),
            EmojiIcon.fromChar((char) 0x27b0),
            EmojiIcon.fromChar((char) 0x3030),
            EmojiIcon.fromChar((char) 0x303d),
            EmojiIcon.fromCodePoint(0x1f531),
            EmojiIcon.fromChar((char) 0x25fc),
            EmojiIcon.fromChar((char) 0x25fb),
            EmojiIcon.fromChar((char) 0x25fe),
            EmojiIcon.fromChar((char) 0x25fd),
            EmojiIcon.fromChar((char) 0x25aa),
            EmojiIcon.fromChar((char) 0x25ab),
            EmojiIcon.fromCodePoint(0x1f53a),
            EmojiIcon.fromCodePoint(0x1f532),
            EmojiIcon.fromCodePoint(0x1f533),
            EmojiIcon.fromChar((char) 0x26ab),
            EmojiIcon.fromChar((char) 0x26aa),
            EmojiIcon.fromCodePoint(0x1f534),
            EmojiIcon.fromCodePoint(0x1f535),
            EmojiIcon.fromCodePoint(0x1f53b),
            EmojiIcon.fromChar((char) 0x2b1c),
            EmojiIcon.fromChar((char) 0x2b1b),
            EmojiIcon.fromCodePoint(0x1f536),
            EmojiIcon.fromCodePoint(0x1f537),
            EmojiIcon.fromCodePoint(0x1f538),
            EmojiIcon.fromCodePoint(0x1f539),
    };
}
